### ISSUE TITLE
Missing Tomcat context.xml and other startup errors when running the customer-service

### ISSUE THREAD

**Issue by docwarems** [opentracing-contrib/java-jfr-tracer#30]
I managed to run the customer-service from the generated customerService.bat, but it gave me the error below followed by a lot more startup errors. What is wrong with my setup?

BTW "Das System kann den angegebenen Pfad nicht finden" doesn mean "file not found".

```
E:\temp\problematic-microservice\robotshop-customer-service\target\bin>customerService.bat
Apr 20, 2021 6:46:43 PM io.jaegertracing.Configuration getTracer
INFORMATION: Initialized tracer=JaegerTracer(version=Java-0.32.0, serviceName=RobotShop-Customer-Service, reporter=CompositeReporter(reporters=[RemoteReporter(sender=UdpSender(), closeEnqueueTimeout=1000), LoggingReporter(logger=org.slf4j.impl.JDK14LoggerAdapter(io.jaegertracing.internal.reporters.LoggingReporter))]), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=PC-MS4, jaeger.version=Java-0.32.0, ip=10.10.11.56}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)
Apr 20, 2021 6:46:43 PM se.hirt.jmc.opentracing.DelegatingJfrTracer initialize
INFORMATION: Using DelegatingJfrTracer to capture contextual information into JFR.
Apr 20, 2021 6:46:44 PM org.apache.catalina.startup.Tomcat getWebappConfigFileFromWar
WARNUNG: Unable to determine web application context.xml E:\temp\problematic-microservice\robotshop-customer-service\target\bin\src\main\webapp
java.io.FileNotFoundException: E:\temp\problematic-microservice\robotshop-customer-service\target\bin\src\main\webapp (Das System kann den angegebenen Pfad nicht finden)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at org.apache.catalina.startup.Tomcat.getWebappConfigFileFromWar(Tomcat.java:1334)
        at org.apache.catalina.startup.Tomcat.getWebappConfigFile(Tomcat.java:1314)
        at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:704)
        at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:665)
        at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:227)
        at se.hirt.examples.robotshop.customerservice.Main.main(Main.java:71)
```

**Comment by docwarems** [comment]
Refered actually to this project - sorry: https://github.com/thegreystone/problematic-microservices
I realized I ran from the wrong workdir.
